#ifndef EVENT_H
#define EVENT_H

enum class Event {
    WINDOW_RESIZE,
    TEXTURE_RESIZE,
    FULLSCREEN_TOGGLE,
    NEW_CANVAS,
    AUDIO_HARDWARE_CHANGE,
    SAVE_PRESET,
    LOAD_PRESET,
    SAVE_COLOR_PRESET,
    LOAD_COLOR_PRESET,
    LOAD_NEW_PICTURE
};

#endif // EVENT_H